/**
 * particleExport.ts
 *
 * Export utilities for particle data in various formats:
 * - PLY (standard point cloud format)
 * - React Three Fiber component
 * - JSON (raw data)
 */

import type { PointCloudData } from './glbToPointCloud';

/**
 * Export point cloud as PLY file (ASCII format)
 * Compatible with MeshLab, CloudCompare, Blender, etc.
 */
export function exportAsPLY(pointCloud: PointCloudData, filename: string = '3dme-particles'): void {
  const { positions, colors, count } = pointCloud;

  // PLY header
  let plyContent = `ply
format ascii 1.0
element vertex ${count}
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header
`;

  // Vertex data
  for (let i = 0; i < count; i++) {
    const x = positions[i * 3].toFixed(6);
    const y = positions[i * 3 + 1].toFixed(6);
    const z = positions[i * 3 + 2].toFixed(6);
    const r = Math.round(colors[i * 3] * 255);
    const g = Math.round(colors[i * 3 + 1] * 255);
    const b = Math.round(colors[i * 3 + 2] * 255);
    plyContent += `${x} ${y} ${z} ${r} ${g} ${b}\n`;
  }

  downloadFile(plyContent, `${filename}.ply`, 'application/octet-stream');
}

/**
 * Export as JSON (compact binary-compatible format)
 */
export function exportAsJSON(pointCloud: PointCloudData, filename: string = '3dme-particles'): void {
  const { positions, colors, normals, sizes, count } = pointCloud;

  const data = {
    version: '1.1',
    generator: '3Dme',
    count,
    // Convert Float32Array to regular arrays for JSON
    positions: Array.from(positions),
    colors: Array.from(colors),
    normals: Array.from(normals),
    // Include sizes if available (adaptive density feature)
    sizes: sizes ? Array.from(sizes) : undefined,
  };

  const json = JSON.stringify(data);
  downloadFile(json, `${filename}.json`, 'application/json');
}

/**
 * Export as React Three Fiber component
 * Generates a complete, copy-paste ready component
 */
export function exportAsReactComponent(
  pointCloud: PointCloudData,
  filename: string = '3dme-particles'
): void {
  const { positions, colors, count } = pointCloud;

  // Compress positions and colors to reasonable precision
  const compressedPositions = Array.from(positions).map(v => Math.round(v * 1000) / 1000);
  const compressedColors = Array.from(colors).map(v => Math.round(v * 1000) / 1000);

  const componentCode = `/**
 * ParticleCloud.tsx
 *
 * Auto-generated by 3Dme (https://github.com/romain-girardi-eng/3Dme)
 *
 * Usage:
 *   import { ParticleCloud } from './ParticleCloud';
 *
 *   function App() {
 *     return (
 *       <Canvas camera={{ position: [0, 0, 100], fov: 50 }}>
 *         <ParticleCloud />
 *         <OrbitControls />
 *       </Canvas>
 *     );
 *   }
 *
 * Dependencies:
 *   npm install three @react-three/fiber @react-three/drei
 */

import { useRef, useMemo } from 'react';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';

// Particle count: ${count.toLocaleString()}
const PARTICLE_COUNT = ${count};

// Compressed particle data (positions: x,y,z per particle)
const POSITIONS = new Float32Array([
${formatArrayForCode(compressedPositions, 12)}
]);

// Compressed color data (r,g,b per particle, 0-1 range)
const COLORS = new Float32Array([
${formatArrayForCode(compressedColors, 12)}
]);

interface ParticleCloudProps {
  size?: number;
  opacity?: number;
  rotationSpeed?: number;
  enableAnimation?: boolean;
}

export function ParticleCloud({
  size = 0.5,
  opacity = 0.9,
  rotationSpeed = 0.001,
  enableAnimation = true,
}: ParticleCloudProps) {
  const pointsRef = useRef<THREE.Points>(null);

  // Create geometry with positions and colors
  const geometry = useMemo(() => {
    const geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.BufferAttribute(POSITIONS.slice(), 3));
    geo.setAttribute('color', new THREE.BufferAttribute(COLORS.slice(), 3));
    return geo;
  }, []);

  // Animation loop
  useFrame((state, delta) => {
    if (pointsRef.current && enableAnimation) {
      pointsRef.current.rotation.y += rotationSpeed;

      // Optional: subtle floating animation
      const positions = pointsRef.current.geometry.attributes.position.array as Float32Array;
      const time = state.clock.elapsedTime;

      for (let i = 0; i < PARTICLE_COUNT; i++) {
        const i3 = i * 3;
        positions[i3 + 1] = POSITIONS[i3 + 1] + Math.sin(time + i * 0.01) * 0.1;
      }
      pointsRef.current.geometry.attributes.position.needsUpdate = true;
    }
  });

  return (
    <points ref={pointsRef} geometry={geometry}>
      <pointsMaterial
        size={size}
        vertexColors
        transparent
        opacity={opacity}
        sizeAttenuation
        depthWrite={false}
        blending={THREE.AdditiveBlending}
      />
    </points>
  );
}

// Alternative: Simple static version (better performance)
export function ParticleCloudStatic({ size = 0.5 }: { size?: number }) {
  const geometry = useMemo(() => {
    const geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.BufferAttribute(POSITIONS.slice(), 3));
    geo.setAttribute('color', new THREE.BufferAttribute(COLORS.slice(), 3));
    return geo;
  }, []);

  return (
    <points geometry={geometry}>
      <pointsMaterial size={size} vertexColors sizeAttenuation />
    </points>
  );
}

export default ParticleCloud;
`;

  downloadFile(componentCode, `${filename}.tsx`, 'text/typescript');
}

/**
 * Export as lightweight React component (separate data file)
 * Better for large particle counts - data in separate JSON file
 */
export function exportAsReactWithSeparateData(
  pointCloud: PointCloudData,
  filename: string = '3dme-particles'
): void {
  const { positions, colors, count } = pointCloud;

  // Component file (lightweight)
  const componentCode = `/**
 * ParticleCloud.tsx
 *
 * Auto-generated by 3Dme (https://github.com/romain-girardi-eng/3Dme)
 * Loads particle data from separate JSON file for better performance.
 *
 * Usage:
 *   import { ParticleCloud } from './ParticleCloud';
 *   import particleData from './${filename}-data.json';
 *
 *   function App() {
 *     return (
 *       <Canvas camera={{ position: [0, 0, 100], fov: 50 }}>
 *         <ParticleCloud data={particleData} />
 *         <OrbitControls />
 *       </Canvas>
 *     );
 *   }
 */

import { useRef, useMemo } from 'react';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';

interface ParticleData {
  count: number;
  positions: number[];
  colors: number[];
}

interface ParticleCloudProps {
  data: ParticleData;
  size?: number;
  opacity?: number;
  rotationSpeed?: number;
}

export function ParticleCloud({
  data,
  size = 0.5,
  opacity = 0.9,
  rotationSpeed = 0.001,
}: ParticleCloudProps) {
  const pointsRef = useRef<THREE.Points>(null);

  const geometry = useMemo(() => {
    const geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.BufferAttribute(new Float32Array(data.positions), 3));
    geo.setAttribute('color', new THREE.BufferAttribute(new Float32Array(data.colors), 3));
    return geo;
  }, [data]);

  useFrame(() => {
    if (pointsRef.current) {
      pointsRef.current.rotation.y += rotationSpeed;
    }
  });

  return (
    <points ref={pointsRef} geometry={geometry}>
      <pointsMaterial
        size={size}
        vertexColors
        transparent
        opacity={opacity}
        sizeAttenuation
        depthWrite={false}
        blending={THREE.AdditiveBlending}
      />
    </points>
  );
}

export default ParticleCloud;
`;

  // Data file (JSON)
  const dataJson = JSON.stringify({
    count,
    positions: Array.from(positions).map(v => Math.round(v * 1000) / 1000),
    colors: Array.from(colors).map(v => Math.round(v * 1000) / 1000),
  });

  // Download both files
  downloadFile(componentCode, `${filename}.tsx`, 'text/typescript');
  setTimeout(() => {
    downloadFile(dataJson, `${filename}-data.json`, 'application/json');
  }, 100);
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function formatArrayForCode(arr: number[], valuesPerLine: number): string {
  const lines: string[] = [];
  for (let i = 0; i < arr.length; i += valuesPerLine) {
    const chunk = arr.slice(i, i + valuesPerLine);
    lines.push('  ' + chunk.join(', ') + ',');
  }
  return lines.join('\n');
}
